#!/bin/bash

tumor_bams=$1; normal_bams=$2; bed=$3
refFlat=$4; reference=$5; mappable_acces=$6; output=$7

#Output directory file
#echo "Where do you want me to store the CNVkit results files?:" $9
# ******** Parameters specific to EXOMEDEPTH ************
# Números de más de un dígito van entre {} 
#echo "Path to the adapted bedfile to be used for the EXOME DEPTH analysis: " ${10}
#echo "Path to the directory where you want to store EXOMEDEPTH results..." ${11}
#echo "Path to the adapted bedfile to be used for the Panelcn.mops analysis:" ${12}
#echo "List the genes of interest for this analysis (separated by a ','):" ${13}
#echo "Name for Panelcn.mops results file:" ${14}
#echo "Path to the directory where you want to store Panelcn.mops results..." ${15}

echo "----------------------------------------------------------------------"
echo "Initializing CNVkit analysis..."
cnvkit.py batch "$tumor_bams"/*.bam --normal "$normal_bams"/*.bam \
    --targets "$bed" --annotate "$refFlat" \
    --fasta "$reference" --access "$mappable_acces" \
    --output-reference "$output"/CNVkit/reference.cnn  --output-dir "$output"/CNVkit \
    --diagram --scatter
echo "-----------------------------------------------------------------------"
echo "Initializing CNVkit calling pipeline"
for entry in "$output"/CNVkit/*.cns
do
  cnvkit.py call "$entry" -o "$entry".call
done
echo "-----------------------------------------------------------------------"
echo "Initializing CNVkit genemetrics analysis"
for entry2 in "$output"/CNVkit/*.cnr
do
	cnvkit.py genemetrics "$entry2" > "$entry2".genemetrics.txt
done
echo "***********************************************************************"
echo "CNVkit analysis... DONE"
echo "***********************************************************************"
