#!/bin/bash
while [[ $# -gt 0 ]]; do
	opt="$1"
	shift;
	current_arg="$1"
	case "$opt" in
"-h"|"--help"      ) echo '''
gecopy version 0.0.1-beta
Usage
	gecopy_docker [options]
Options
	-i --input		Folder with BAM files
	-o --output		Output folder location
	-r --ref		Reference genome file
	-n --normal		Folder with BAM files of normals
	-c --bed-cnvkit		File with regions of interest
	-e --bed-exomedepth File with regions of interest 
	-p --bed-panelcnmops File with regions of interest
	-m --mappable File with mappable regions
	-f --refFlat File refFlat
''';  exit 1;;
"-i"|"--input"      ) tumor_bams="$1"; shift;;
"-n"|"--normal"      ) normal_bams="$1"; shift;;
"-o"|"--output"      ) output="$1"; shift;;
"-r"|"--reference"      ) reference="$1"; shift;;
"-c"|"--bed-cnvkit"      ) bed_cnvkit="$1"; shift;;
"-f"|"--refFlat"      ) refFlat="$1"; shift;;
"-m"|"--mappable"      ) mappable="$1"; shift;;
"-e"|"--bed-exomedepth"      ) bed_exomedepth="$1"; shift;;
"-p"|"--bed-panelcnmops"      ) bed_panelcnmops="$1"; shift;;
"-g"|"--genes-panelcnmops"      ) genes_panelcnmops="$1"; shift;;
	esac
done

#tumor_bams=$1; normal_bams=$2; bed_cnvkit=$3
#refFlat=$4; reference=$5; mappable=$6; output=$7
#bed_exomedepth=$8; bed_panelcnmops=$9; genes_panelcnmops=${10}

figlet gecopy
#============================= Pathways extraction ============================#
dir=$(pwd) ; dir_home=$(echo $dir | cut -d'/' -f2)

# Clasificación de rutas absolutas y relativas
pathway_val () {
	if [ "$1" = "False" ]; then
		var=$1
	elif [ "$(echo $1 | cut -d'/' -f2)" != "$dir_home" ]; then #ruta relativa
		var=$dir/$1
	else #ruta absoluta
		var=$1
	fi
}

pathway_val $tumor_bams ; tumor_bams=$var
pathway_val $normal_bams ; normal_bams=$var
pathway_val $bed_cnvkit ; bed_cnvkit=$var
pathway_val $refFlat ; refFlat=$var
pathway_val $reference ; reference=$var
pathway_val $mappable ; mappable=$var
pathway_val $output ; output=$var
pathway_val $bed_exomedepth ; bed_exomedepth=$var
pathway_val $bed_panelcnmops ; bed_panelcnmops=$var

mkdir $output/CNVkit
mkdir $output/ExomeDepth
mkdir $output/Panelcnmops

figlet cnvkit
docker run -v /${dir_home}:/${dir_home} -it ambrizbiotech/cnvkit cnvkit_custom $tumor_bams $normal_bams $bed_cnvkit $refFlat $reference $mappable $output

figlet exomedepth
docker run -v /${dir_home}:/${dir_home} -it ambrizbiotech/exomedepth Rscript /usr/bin/exome_depth_bash.R $tumor_bams $normal_bams $reference $bed_exomedepth $output

figlet panelcnmops
docker run -v /${dir_home}:/${dir_home} -it ambrizbiotech/panelcnmops Rscript /usr/bin/panelcn_mops_bash.R $tumor_bams $normal_bams $bed_panelcnmops $genes_panelcnmops $output
