#!/bin/bash
tumor_bams=$1; normal_bams=$2; bed_cnvkit=$3
refFlat=$4; reference=$5; mappable=$6; output=$7
#era el 10
bed_exomedepth=$8
# era el 12 y 13
bed_panelcnmops=$9
genes_panelcnmops=${10}

figlet gecopy
#============================= Pathways extraction ============================#
dir=$(pwd) ; dir_home=$(echo $dir | cut -d'/' -f2)

# Clasificación de rutas absolutas y relativas
pathway_val () {
	if [ "$1" = "False" ]; then
		var=$1
	elif [ "$(echo $1 | cut -d'/' -f2)" != "$dir_home" ]; then #ruta relativa
		var=$dir/$1
	else #ruta absoluta
		var=$1
	fi
}

pathway_val $tumor_bams ; tumor_bams=$var
pathway_val $normal_bams ; normal_bams=$var
pathway_val $bed_cnvkit ; bed_cnvkit=$var
pathway_val $refFlat ; refFlat=$var
pathway_val $reference ; reference=$var
pathway_val $mappable ; mappable=$var
pathway_val $output ; output=$var
pathway_val $bed_exomedepth ; bed_exomedepth=$var
pathway_val $bed_panelcnmops ; bed_panelcnmops=$var

mkdir $output/CNVkit
mkdir $output/ExomeDepth
mkdir $output/Panelcnmops

figlet cnvkit
docker run -v /${dir_home}:/${dir_home} -it ambrizbiotech/cnvkit cnvkit_custom $tumor_bams $normal_bams $bed_cnvkit $refFlat $reference $mappable $output

figlet exomedepth
docker run -v /${dir_home}:/${dir_home} -it ambrizbiotech/exomedepth Rscript /usr/bin/exome_depth_bash.R $tumor_bams $normal_bams $reference $bed_exomedepth $output

figlet panelcnmops
docker run -v /${dir_home}:/${dir_home} -it ambrizbiotech/panelcnmops Rscript /usr/bin/panelcn_mops_bash.R $tumor_bams $normal_bams $bed_panelcnmops $genes_panelcnmops $output
